on:

  push:
  
  schedule:
    - cron: "*/5 * * * *"

name: CI

jobs:

  unittest:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Run full test
      run:
        make test
